// Generated by build_schools.py: do not edit by hand. Rebuild after adding interviews.
window.DOCSTORY_SCHOOLS = [
 {
  "slug": "albany-medical-college",
  "name": "Albany Medical College",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "baylor-college-of-medicine",
  "name": "Baylor College of Medicine",
  "type": "md",
  "interviews": 2
 },
 {
  "slug": "brody-school-of-medicine",
  "name": "Brody School of Medicine at East Carolina University",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "california-university-of-science-and-medicine",
  "name": "California University of Science and Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "rosalind-franklin-university",
  "name": "Chicago Medical School at Rosalind Franklin University",
  "type": "md",
  "interviews": 2
 },
 {
  "slug": "creighton-university-school-of-medicine",
  "name": "Creighton University School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "ucla-geffen-school-of-medicine",
  "name": "David Geffen School of Medicine at UCLA",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "drexel-university-college-of-medicine",
  "name": "Drexel University College of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "duke-university-school-of-medicine",
  "name": "Duke University School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "eastern-virginia-medical-school",
  "name": "Eastern Virginia Medical School",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "florida-state-university-college-of-medicine",
  "name": "Florida State University College of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "harvard-medical-school",
  "name": "Harvard Medical School",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "indiana-university-school-of-medicine",
  "name": "Indiana University School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "johns-hopkins-school-of-medicine",
  "name": "Johns Hopkins School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "kentucky-college-of-osteopathic-medicine",
  "name": "Kentucky College of Osteopathic Medicine",
  "type": "do",
  "interviews": 1
 },
 {
  "slug": "mayo-clinic-school-of-medicine",
  "name": "Mayo Clinic Alix School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "medical-college-of-georgia",
  "name": "Medical College of Georgia at Augusta University",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "medical-college-of-wisconsin",
  "name": "Medical College of Wisconsin",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "midwestern-chicago-college-of-osteopathic-medicine",
  "name": "Midwestern University Chicago College of Osteopathic Medicine",
  "type": "do",
  "interviews": 1
 },
 {
  "slug": "new-york-medical-college",
  "name": "New York Medical College",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "northwestern-feinberg-school-of-medicine",
  "name": "Northwestern Feinberg School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "rush-medical-college",
  "name": "Rush Medical College",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "southern-illinois-university-school-of-medicine",
  "name": "Southern Illinois University School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "tcu-burnett-school-of-medicine",
  "name": "TCU Burnett School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "texas-a-and-m-college-of-medicine",
  "name": "Texas A&M University Naresh K. Vashisht College of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "touro-college-of-osteopathic-medicine",
  "name": "Touro College of Osteopathic Medicine",
  "type": "do",
  "interviews": 2
 },
 {
  "slug": "tulane-university-school-of-medicine",
  "name": "Tulane University School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "university-of-alabama-birmingham",
  "name": "UAB Heersink School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "uc-irvine-school-of-medicine",
  "name": "UC Irvine School of Medicine",
  "type": "md",
  "interviews": 3
 },
 {
  "slug": "uc-san-diego-school-of-medicine",
  "name": "UC San Diego School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "university-of-massachusetts-medical-school",
  "name": "UMass Chan Medical School",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "university-of-cincinnati-college-of-medicine",
  "name": "University of Cincinnati College of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "university-of-florida-college-of-medicine",
  "name": "University of Florida College of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "university-of-iowa-carver-college-of-medicine",
  "name": "University of Iowa Carver College of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "university-of-miami-miller-school-of-medicine",
  "name": "University of Miami Miller School of Medicine",
  "type": "md",
  "interviews": 2
 },
 {
  "slug": "university-of-oklahoma-college-of-medicine",
  "name": "University of Oklahoma College of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "ut-health-science-center",
  "name": "University of Tennessee Health Science Center College of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "usc-keck-school-of-medicine",
  "name": "USC Keck School of Medicine",
  "type": "md",
  "interviews": 3
 },
 {
  "slug": "morsani-college-of-medicine",
  "name": "USF Health Morsani College of Medicine",
  "type": "md",
  "interviews": 2
 },
 {
  "slug": "virginia-commonwealth-university",
  "name": "VCU School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "wayne-state-school-of-medicine",
  "name": "Wayne State University School of Medicine",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "weill-cornell-medical-college",
  "name": "Weill Cornell Medical College",
  "type": "md",
  "interviews": 1
 },
 {
  "slug": "western-university-osteopathic",
  "name": "Western University College of Osteopathic Medicine of the Pacific",
  "type": "do",
  "interviews": 1
 },
 {
  "slug": "yale-school-of-medicine",
  "name": "Yale School of Medicine",
  "type": "md",
  "interviews": 1
 }
];
