// Generated by build_schools.py from content/: do not edit by hand.
window.DOCSTORY_SITE = {
 "stats": {
  "schools": 40,
  "md": 37,
  "do": 3,
  "states": 23,
  "interviews": 49,
  "byYear": {
   "1": 14,
   "2": 24,
   "3": 9,
   "4": 2
  }
 },
 "schools": [
  {
   "slug": "harvard-medical-school",
   "name": "Harvard Medical School",
   "shortName": "HMS",
   "city": "Boston, MA",
   "state": "MA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "yale-school-of-medicine",
   "name": "Yale School of Medicine",
   "shortName": "Yale",
   "city": "New Haven, CT",
   "state": "CT",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "johns-hopkins-school-of-medicine",
   "name": "Johns Hopkins School of Medicine",
   "shortName": "Johns Hopkins",
   "city": "Baltimore, MD",
   "state": "MD",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "duke-university-school-of-medicine",
   "name": "Duke University School of Medicine",
   "shortName": "Duke",
   "city": "Durham, NC",
   "state": "NC",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "weill-cornell-medical-college",
   "name": "Weill Cornell Medical College",
   "shortName": "Weill Cornell",
   "city": "New York, NY",
   "state": "NY",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "northwestern-feinberg-school-of-medicine",
   "name": "Northwestern Feinberg School of Medicine",
   "shortName": "Feinberg",
   "city": "Chicago, IL",
   "state": "IL",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "university-of-alabama-birmingham",
   "name": "UAB Heersink School of Medicine",
   "shortName": "UAB",
   "city": "Birmingham, AL",
   "state": "AL",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "uc-irvine-school-of-medicine",
   "name": "UC Irvine School of Medicine",
   "shortName": "UCI",
   "city": "Irvine, CA",
   "state": "CA",
   "type": "md",
   "interviews": 3
  },
  {
   "slug": "university-of-massachusetts-medical-school",
   "name": "UMass Chan Medical School",
   "shortName": "UMass Chan",
   "city": "Worcester, MA",
   "state": "MA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "uc-san-diego-school-of-medicine",
   "name": "UC San Diego School of Medicine",
   "shortName": "UC San Diego",
   "city": "La Jolla, CA",
   "state": "CA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "mayo-clinic-school-of-medicine",
   "name": "Mayo Clinic Alix School of Medicine",
   "shortName": "Mayo Clinic",
   "city": "Rochester, MN",
   "state": "MN",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "tulane-university-school-of-medicine",
   "name": "Tulane University School of Medicine",
   "shortName": "Tulane",
   "city": "New Orleans, LA",
   "state": "LA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "drexel-university-college-of-medicine",
   "name": "Drexel University College of Medicine",
   "shortName": "Drexel",
   "city": "Philadelphia, PA",
   "state": "PA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "creighton-university-school-of-medicine",
   "name": "Creighton University School of Medicine",
   "shortName": "Creighton",
   "city": "Omaha, NE",
   "state": "NE",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "morsani-college-of-medicine",
   "name": "USF Health Morsani College of Medicine",
   "shortName": "USF Morsani",
   "city": "Tampa, FL",
   "state": "FL",
   "type": "md",
   "interviews": 2
  },
  {
   "slug": "rosalind-franklin-university",
   "name": "Chicago Medical School at Rosalind Franklin University",
   "shortName": "Chicago Medical School",
   "city": "North Chicago, IL",
   "state": "IL",
   "type": "md",
   "interviews": 2
  },
  {
   "slug": "usc-keck-school-of-medicine",
   "name": "USC Keck School of Medicine",
   "shortName": "USC Keck",
   "city": "Los Angeles, CA",
   "state": "CA",
   "type": "md",
   "interviews": 2
  },
  {
   "slug": "western-university-osteopathic",
   "name": "Western University College of Osteopathic Medicine of the Pacific",
   "shortName": "COMP",
   "city": "Pomona, CA",
   "state": "CA",
   "type": "do",
   "interviews": 1
  },
  {
   "slug": "virginia-commonwealth-university",
   "name": "VCU School of Medicine",
   "shortName": "VCU",
   "city": "Richmond, VA",
   "state": "VA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "kentucky-college-of-osteopathic-medicine",
   "name": "Kentucky College of Osteopathic Medicine",
   "shortName": "KYCOM",
   "city": "Pikeville, KY",
   "state": "KY",
   "type": "do",
   "interviews": 1
  },
  {
   "slug": "medical-college-of-wisconsin",
   "name": "Medical College of Wisconsin",
   "shortName": "MCW",
   "city": "Milwaukee, WI",
   "state": "WI",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "wayne-state-school-of-medicine",
   "name": "Wayne State University School of Medicine",
   "shortName": "Wayne State",
   "city": "Detroit, MI",
   "state": "MI",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "baylor-college-of-medicine",
   "name": "Baylor College of Medicine",
   "shortName": "Baylor",
   "city": "Houston, TX",
   "state": "TX",
   "type": "md",
   "interviews": 2
  },
  {
   "slug": "ut-health-science-center",
   "name": "University of Tennessee Health Science Center College of Medicine",
   "shortName": "UTHSC",
   "city": "Memphis, TN",
   "state": "TN",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "ucla-geffen-school-of-medicine",
   "name": "David Geffen School of Medicine at UCLA",
   "shortName": "UCLA",
   "city": "Los Angeles, CA",
   "state": "CA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "university-of-florida-college-of-medicine",
   "name": "University of Florida College of Medicine",
   "shortName": "UF",
   "city": "Gainesville, FL",
   "state": "FL",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "florida-state-university-college-of-medicine",
   "name": "Florida State University College of Medicine",
   "shortName": "FSU",
   "city": "Tallahassee, FL",
   "state": "FL",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "medical-college-of-georgia",
   "name": "Medical College of Georgia at Augusta University",
   "shortName": "MCG",
   "city": "Augusta, GA",
   "state": "GA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "california-university-of-science-and-medicine",
   "name": "California University of Science and Medicine",
   "shortName": "CUSM",
   "city": "Colton, CA",
   "state": "CA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "indiana-university-school-of-medicine",
   "name": "Indiana University School of Medicine",
   "shortName": "IUSM",
   "city": "Indianapolis, IN",
   "state": "IN",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "southern-illinois-university-school-of-medicine",
   "name": "Southern Illinois University School of Medicine",
   "shortName": "SIU",
   "city": "Springfield, IL",
   "state": "IL",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "touro-college-of-osteopathic-medicine",
   "name": "Touro College of Osteopathic Medicine",
   "shortName": "TouroCOM",
   "city": "Middletown, NY",
   "state": "NY",
   "type": "do",
   "interviews": 2
  },
  {
   "slug": "university-of-cincinnati-college-of-medicine",
   "name": "University of Cincinnati College of Medicine",
   "shortName": "UC",
   "city": "Cincinnati, OH",
   "state": "OH",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "new-york-medical-college",
   "name": "New York Medical College",
   "shortName": "NYMC",
   "city": "Valhalla, NY",
   "state": "NY",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "university-of-miami-miller-school-of-medicine",
   "name": "University of Miami Miller School of Medicine",
   "shortName": "Miami",
   "city": "Miami, FL",
   "state": "FL",
   "type": "md",
   "interviews": 2
  },
  {
   "slug": "university-of-iowa-carver-college-of-medicine",
   "name": "University of Iowa Carver College of Medicine",
   "shortName": "Iowa",
   "city": "Iowa City, IA",
   "state": "IA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "eastern-virginia-medical-school",
   "name": "Eastern Virginia Medical School",
   "shortName": "EVMS",
   "city": "Norfolk, VA",
   "state": "VA",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "rush-medical-college",
   "name": "Rush Medical College",
   "shortName": "Rush",
   "city": "Chicago, IL",
   "state": "IL",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "tcu-burnett-school-of-medicine",
   "name": "TCU Burnett School of Medicine",
   "shortName": "TCU",
   "city": "Fort Worth, TX",
   "state": "TX",
   "type": "md",
   "interviews": 1
  },
  {
   "slug": "albany-medical-college",
   "name": "Albany Medical College",
   "shortName": "AMC",
   "city": "Albany, NY",
   "state": "NY",
   "type": "md",
   "interviews": 1
  }
 ],
 "interviews": [
  {
   "name": "Abraham Cheloff",
   "year": "MS2",
   "school": "Harvard Medical School",
   "schoolSlug": "harvard-medical-school",
   "studentSlug": "abraham-cheloff",
   "city": "Boston, MA",
   "quote": "The passion of the educators here, both preclinical and clinical, has really struck me. … The number of possibilities at HMS truly feels endless, and the faculty support only makes those possibilities even more attainable."
  },
  {
   "name": "Hadrian Mendoza",
   "year": "MS2",
   "school": "Yale School of Medicine",
   "schoolSlug": "yale-school-of-medicine",
   "studentSlug": "hadrian-mendoza",
   "city": "New Haven, CT",
   "quote": "With Pass/Fail grading and no ranking system or AOA, we are able to collaborate with each other and stay engaged in our lives outside of medicine. … I think of it as a gunner-free zone."
  },
  {
   "name": "Will Tobolowsky",
   "year": "MS3",
   "school": "Johns Hopkins School of Medicine",
   "schoolSlug": "johns-hopkins-school-of-medicine",
   "studentSlug": "will-tobolowsky",
   "city": "Baltimore, MD",
   "quote": "I wouldn't let an area influence your choice of medical school too much. Remember, you're going to medical school to hopefully 1) help people, 2) learn."
  },
  {
   "name": "Alex",
   "year": "MS2",
   "school": "Duke University School of Medicine",
   "schoolSlug": "duke-university-school-of-medicine",
   "studentSlug": "alex",
   "city": "Durham, NC",
   "quote": "For me, the most important thing was ultimately the happiness of the student body. … I truly felt like the Duke students were some of the happiest students I met on the interview trail."
  },
  {
   "name": "Annie Yau",
   "year": "MS1",
   "school": "Weill Cornell Medical College",
   "schoolSlug": "weill-cornell-medical-college",
   "studentSlug": "annie-yau",
   "city": "New York, NY",
   "quote": "We have a class of just over 100 students so it helps make our class very tight knit. Most of us live in the same building during the first year, which also helps bring us together."
  },
  {
   "name": "Regine Goh",
   "year": "MS3",
   "school": "Northwestern Feinberg School of Medicine",
   "schoolSlug": "northwestern-feinberg-school-of-medicine",
   "studentSlug": "regine-goh",
   "city": "Chicago, IL",
   "quote": "Chicago has so many unique neighborhoods and working at these free clinics is a great opportunity to work with different under-served communities."
  },
  {
   "name": "Emily Hayward",
   "year": "MS3 (MD/PhD)",
   "school": "UAB Heersink School of Medicine",
   "schoolSlug": "university-of-alabama-birmingham",
   "studentSlug": "emily-hayward",
   "city": "Birmingham, AL",
   "quote": "I have realized that I am not here to become a better student or test-taker. I am in medical school to become a better physician, and there is so much more to that than obtaining a perfect score."
  },
  {
   "name": "Alexa Lucas",
   "year": "MS1",
   "school": "UC Irvine School of Medicine",
   "schoolSlug": "uc-irvine-school-of-medicine",
   "studentSlug": "alexa-lucas",
   "city": "Irvine, CA",
   "quote": "I think the global health aspect is super unique and incredible (but a lot of work!)"
  },
  {
   "name": "Arnie Shah",
   "year": "MS1",
   "school": "UC Irvine School of Medicine",
   "schoolSlug": "uc-irvine-school-of-medicine",
   "studentSlug": "arnie-shah",
   "city": "Irvine, CA",
   "quote": "I think UC Irvine has done a really good job creating a very collaborative class with a wide variety of skills and interest. Knowing everyone at your school is really different coming from a big university. But I like it because it feels a lot more like family."
  },
  {
   "name": "Steven Tohmasi",
   "year": "MS2",
   "school": "UC Irvine School of Medicine",
   "schoolSlug": "uc-irvine-school-of-medicine",
   "studentSlug": "steven-tohmasi",
   "city": "Irvine, CA",
   "quote": "Each year, around 30-40 med students will spend the summer between their 1st and 2nd year teaching ultrasound internationally and conducting ultrasound-related research."
  },
  {
   "name": "Prithwijit Roychowdhury",
   "year": "MS2",
   "school": "UMass Chan Medical School",
   "schoolSlug": "university-of-massachusetts-medical-school",
   "studentSlug": "prithwijit-roychowdhury",
   "city": "Worcester, MA",
   "quote": "The culture of our school is always positive and extremely supportive. There is never a time where I feel like I cannot look to older students or my faculty mentors for advice or guidance."
  },
  {
   "name": "Neela",
   "year": "MS1",
   "school": "UC San Diego School of Medicine",
   "schoolSlug": "uc-san-diego-school-of-medicine",
   "studentSlug": "neela",
   "city": "La Jolla, CA",
   "quote": "What really struck me at UCSD was that the first years seemed really, really happy–WAY happier than I thought possible at a medical school."
  },
  {
   "name": "Arya Shah",
   "year": "MS4",
   "school": "Mayo Clinic Alix School of Medicine",
   "schoolSlug": "mayo-clinic-school-of-medicine",
   "studentSlug": "arya-shah",
   "city": "Rochester, MN",
   "quote": "The small size has been great. I feel like I'm in a community in which I know, not only all of my classmates, but also all of my faculty, administrators, mentors, and preceptors by name."
  },
  {
   "name": "David",
   "year": "MS2",
   "school": "Tulane University School of Medicine",
   "schoolSlug": "tulane-university-school-of-medicine",
   "studentSlug": "david",
   "city": "New Orleans, LA",
   "quote": "Many students in my class will tell you that their favorite aspect of TUSOM is the people in our class. Tulane has a way of selecting students that have very different and unique upbringings, experiences, and interests."
  },
  {
   "name": "Jonathan Acosta",
   "year": "MS2",
   "school": "Drexel University College of Medicine",
   "schoolSlug": "drexel-university-college-of-medicine",
   "studentSlug": "jonathan-acosta",
   "city": "Philadelphia, PA",
   "quote": "I have a large group of friends, and the atmosphere is very non-competitive which makes interacting with other students a good experience."
  },
  {
   "name": "Eric Nguyen",
   "year": "MS2",
   "school": "Creighton University School of Medicine",
   "schoolSlug": "creighton-university-school-of-medicine",
   "studentSlug": "eric-nguyen",
   "city": "Omaha, NE",
   "quote": "We were taught to not only understand how a patient's ailment affected one's bodily function, but also how it affected one's daily life."
  },
  {
   "name": "Brian James",
   "year": "MS2",
   "school": "USF Health Morsani College of Medicine",
   "schoolSlug": "morsani-college-of-medicine",
   "studentSlug": "brian-james",
   "city": "Tampa, FL",
   "quote": "The faculty here are very receptive to feedback and will accommodate almost immediately. Also we have a lot of standardized patients … to help hone in our skills."
  },
  {
   "name": "Chetna Thawani",
   "year": "M2",
   "school": "USF Health Morsani College of Medicine",
   "schoolSlug": "morsani-college-of-medicine",
   "studentSlug": "chetna-thawani",
   "city": "Tampa, FL",
   "quote": "We have these things kind of like Hogwarts houses, called Collegias, which are 'learning communities' that we're split into for things like anatomy lab, doctoring groups, etc."
  },
  {
   "name": "Allison Martin",
   "year": "MS2",
   "school": "Chicago Medical School at Rosalind Franklin University",
   "schoolSlug": "rosalind-franklin-university",
   "studentSlug": "allison-martin",
   "city": "North Chicago, IL",
   "quote": "We get to rotate through most of the hospitals in Chicago-land plus many small clinics."
  },
  {
   "name": "Drew Weinstein",
   "year": "MS2",
   "school": "Chicago Medical School at Rosalind Franklin University",
   "schoolSlug": "rosalind-franklin-university",
   "studentSlug": "drew-weinstein",
   "city": "North Chicago, IL",
   "quote": "On the weekends we can take a train 45 minutes into the city to enjoy the night life or just to explore. During rotations third and fourth year we move downtown which is awesome."
  },
  {
   "name": "Dominic Carusillo",
   "year": "MS1",
   "school": "USC Keck School of Medicine",
   "schoolSlug": "usc-keck-school-of-medicine",
   "studentSlug": "dominic-carusillo",
   "city": "Los Angeles, CA",
   "quote": "I think shadowing has been the most valuable extracurricular thing I've done so far. There are so many resources and opportunities to see really cool specialties, and as a med student, attendings are very excited to show you all the cool things they do."
  },
  {
   "name": "Sam Teles",
   "year": "MS1",
   "school": "USC Keck School of Medicine",
   "schoolSlug": "usc-keck-school-of-medicine",
   "studentSlug": "sam-teles",
   "city": "Los Angeles, CA",
   "quote": "Being able to see patients at County is special because these are people who are grateful for your help and for someone that will listen to them. … So being able to make a difference with people at County simply by paying attention to them is special and probably the best part about where our campus is located."
  },
  {
   "name": "Chuck Chan",
   "year": "OSM1",
   "school": "Western University College of Osteopathic Medicine of the Pacific",
   "schoolSlug": "western-university-osteopathic",
   "studentSlug": "chuck-chan",
   "city": "Pomona, CA",
   "quote": "We have about 8 patient encounters per semester which initially sounds annoying, but is such good practice to deal with patients later."
  },
  {
   "name": "Chris",
   "year": "MS2",
   "school": "VCU School of Medicine",
   "schoolSlug": "virginia-commonwealth-university",
   "studentSlug": "chris",
   "city": "Richmond, VA",
   "quote": "Being inside the homes and neighborhoods of our patients gives a unique perspective and helped me develop a greater appreciation for the challenges many people face when it comes to balancing life challenges and their health."
  },
  {
   "name": "Jeremy Storck",
   "year": "OSM3",
   "school": "Kentucky College of Osteopathic Medicine",
   "schoolSlug": "kentucky-college-of-osteopathic-medicine",
   "studentSlug": "jeremy-storck",
   "city": "Pikeville, KY",
   "quote": "There wasn't anything specific about it that got me to accept the offer, but rather just a feeling of 'You belong here, this is where you're going to medical school' while I was there."
  },
  {
   "name": "Austin Dopp",
   "year": "MS2",
   "school": "Medical College of Wisconsin",
   "schoolSlug": "medical-college-of-wisconsin",
   "studentSlug": "austin-dopp",
   "city": "Milwaukee, WI",
   "quote": "The culture at my school is very supportive. I am in a class of around 200 and so while you think you may get forgotten or left out, I have never felt that way."
  },
  {
   "name": "Nik",
   "year": "MS1",
   "school": "Wayne State University School of Medicine",
   "schoolSlug": "wayne-state-school-of-medicine",
   "studentSlug": "nik",
   "city": "Detroit, MI",
   "quote": "Students at Wayne take pride for being so diverse and multi cultured … I'm no longer pursuing medicine for me, I'm doing it for my future patients."
  },
  {
   "name": "Justin",
   "year": "MS1",
   "school": "Baylor College of Medicine",
   "schoolSlug": "baylor-college-of-medicine",
   "studentSlug": "justin",
   "city": "Houston, TX",
   "quote": "While gunners exist, they don't actively undermine other students. We are very collaborative and love to relax on the weekends or at the end of the terms."
  },
  {
   "name": "Michele Cabeza",
   "year": "MS1",
   "school": "Baylor College of Medicine",
   "schoolSlug": "baylor-college-of-medicine",
   "studentSlug": "michele-cabeza",
   "city": "Houston, TX",
   "quote": "Firstly, it is a huge plus that our preclinical curriculum is true Pass/Fail. This helps to make the environment way less competitive than schools that rank their students."
  },
  {
   "name": "Jay Patel",
   "year": "MS1",
   "school": "University of Tennessee Health Science Center College of Medicine",
   "schoolSlug": "ut-health-science-center",
   "studentSlug": "jay-patel",
   "city": "Memphis, TN",
   "quote": "Everyone is supportive of each other before and after exams from the outset, making medical school feel more manageable and less daunting."
  },
  {
   "name": "Tim Ellis-Caleo",
   "year": "MS4",
   "school": "David Geffen School of Medicine at UCLA",
   "schoolSlug": "ucla-geffen-school-of-medicine",
   "studentSlug": "tim-ellis-caleo",
   "city": "Los Angeles, CA",
   "quote": "The real strength of UCLA lies in the excellent clinical training across a variety of sites. Being exposed to strong residents and faculty who will delegate significant responsibility to you as a medical student is the best way to maximize your learning during third year."
  },
  {
   "name": "Anonymous",
   "year": "MS2",
   "school": "University of Florida College of Medicine",
   "schoolSlug": "university-of-florida-college-of-medicine",
   "studentSlug": "anonymous-ms2",
   "city": "Gainesville, FL",
   "quote": "There is a decent balance of academics and life outside of school. Football games/tailgating and sports are a big part of the culture here and there is a good amount of school spirit."
  },
  {
   "name": "Anonymous",
   "year": "MS3",
   "school": "Florida State University College of Medicine",
   "schoolSlug": "florida-state-university-college-of-medicine",
   "studentSlug": "anonymous-ms3",
   "city": "Tallahassee, FL",
   "quote": "Fantastic student support system. Tight knit class. Regional campus rotation set-up (because of this, we are almost always rotating with physician one on one and get wayyyy more exposure to things other med students do not)."
  },
  {
   "name": "Catherine Boatman",
   "year": "M2",
   "school": "Medical College of Georgia at Augusta University",
   "schoolSlug": "medical-college-of-georgia",
   "studentSlug": "catherine-boatman",
   "city": "Augusta, GA",
   "quote": "Our faculty and staff is so incredibly supportive, and I didn’t realize how important that would be while I was interviewing at different medical schools. So much of the potential stress at MCG is removed because our instructors really care about helping us in any way they can."
  },
  {
   "name": "Bao Vu",
   "year": "MS1",
   "school": "California University of Science and Medicine",
   "schoolSlug": "california-university-of-science-and-medicine",
   "studentSlug": "bao-vu",
   "city": "Colton, CA",
   "quote": "We are a Pass/Fail school so the culture at my school is very very chill and laid back. Everyone is super nice and we are always willing to share notes or support each other in times of need."
  },
  {
   "name": "Austin Wininger",
   "year": "MS3",
   "school": "Indiana University School of Medicine",
   "schoolSlug": "indiana-university-school-of-medicine",
   "studentSlug": "austin-wininger",
   "city": "Indianapolis, IN",
   "quote": "The ability to work in a community setting and in a major city with level 1 trauma gave me a great foundation of clinical knowledge."
  },
  {
   "name": "Alexander Worix",
   "year": "MS2",
   "school": "Southern Illinois University School of Medicine",
   "schoolSlug": "southern-illinois-university-school-of-medicine",
   "studentSlug": "alexander-worix",
   "city": "Springfield, IL",
   "quote": "SIU SOM has a reputation with multiple residency programs for being a clinical-heavy medical institution and really preparing our students to train after graduation. We are even known to be pioneers of the “standardized patient.”"
  },
  {
   "name": "Brittany Stelmar",
   "year": "MS2",
   "school": "Touro College of Osteopathic Medicine",
   "schoolSlug": "touro-college-of-osteopathic-medicine",
   "studentSlug": "brittany-stelmar",
   "city": "Middletown, NY",
   "quote": "I like how involved the professors are with all of us. If anyone gets a subpar test grade, they reach out via email to schedule a meeting and set up tutoring. Touro is extremely proactive about giving people help when they need it."
  },
  {
   "name": "Wei Ming Liang",
   "year": "OMS-2",
   "school": "Touro College of Osteopathic Medicine",
   "schoolSlug": "touro-college-of-osteopathic-medicine",
   "studentSlug": "wei-ming-liang",
   "city": "Middletown, NY",
   "quote": "Each student gets an upperclassman as a mentor the minute they begin their first year, as well as a faculty advisor. These mentors have been instrumental in providing guidance, support, and advice throughout my journey in medical school."
  },
  {
   "name": "Priya Sorab",
   "year": "MS2",
   "school": "University of Cincinnati College of Medicine",
   "schoolSlug": "university-of-cincinnati-college-of-medicine",
   "studentSlug": "priya-sorab",
   "city": "Cincinnati, OH",
   "quote": "Once every other week, each student goes to a doctor’s office to see patients-yes, we get to do this in our first and second years. This was my favorite part of the week!"
  },
  {
   "name": "Nick Bacher",
   "year": "MS3",
   "school": "New York Medical College",
   "schoolSlug": "new-york-medical-college",
   "studentSlug": "nick-bacher",
   "city": "Valhalla, NY",
   "quote": "We have a Friendsgiving event launched this year by some particularly enterprising first years and now expanded to include all four class years. … It’s a really tight knit community here, and this type of thing is exactly what NYMC is about."
  },
  {
   "name": "Todd Jackson",
   "year": "MS3",
   "school": "University of Miami Miller School of Medicine",
   "schoolSlug": "university-of-miami-miller-school-of-medicine",
   "studentSlug": "todd-jackson",
   "city": "Miami, FL",
   "quote": "The biggest strength is the breadth of diversity that the institution sees and also learning how to care for some of the most disadvantaged, at-risk populations in the nation."
  },
  {
   "name": "Zach Donato",
   "year": "MS2",
   "school": "University of Miami Miller School of Medicine",
   "schoolSlug": "university-of-miami-miller-school-of-medicine",
   "studentSlug": "zach-donato",
   "city": "Miami, FL",
   "quote": "Miami is a very service-oriented school. The DOCS clinic is a popular activity at our school, with over 70% of students participating."
  },
  {
   "name": "Gabriel Conley",
   "year": "MS2",
   "school": "University of Iowa Carver College of Medicine",
   "schoolSlug": "university-of-iowa-carver-college-of-medicine",
   "studentSlug": "gabriel-conley",
   "city": "Iowa City, IA",
   "quote": "The culture at Iowa feels incredibly collaborative to me. We have a plethora of tutor availability (from other classmates), and we do a ton of note-sharing as well."
  },
  {
   "name": "Rossen Kirkov",
   "year": "MS3",
   "school": "Eastern Virginia Medical School",
   "schoolSlug": "eastern-virginia-medical-school",
   "studentSlug": "rossen-kirkov",
   "city": "Norfolk, VA",
   "quote": "We are all very close to each other and help each other. There is no sense of competitiveness between classmates, we all help each other out."
  },
  {
   "name": "Emily He",
   "year": "MS1",
   "school": "Rush Medical College",
   "schoolSlug": "rush-medical-college",
   "studentSlug": "emily-he",
   "city": "Chicago, IL",
   "quote": "One of the main things that drew me to Rush and what I love most about the school is its overwhelming commitment to the community. Every aspect of volunteer work always goes back to the community."
  },
  {
   "name": "Kyung Park",
   "year": "MS2",
   "school": "TCU Burnett School of Medicine",
   "schoolSlug": "tcu-burnett-school-of-medicine",
   "studentSlug": "kyung-park",
   "city": "Fort Worth, TX",
   "quote": "Also being in a class of 60 students, the faculty are incredibly invested in your success and often know us by name, which was a big departure from undergraduate when I could be in a course with over 900 students."
  },
  {
   "name": "Ana Khatia",
   "year": "MS2",
   "school": "Albany Medical College",
   "schoolSlug": "albany-medical-college",
   "studentSlug": "ana-khatia",
   "city": "Albany, NY",
   "quote": "The students at AMC very much have the \"we are all in this together\" mentality. I feel very lucky to attend a medical school were we support each other and celebrate each others accomplishments."
  }
 ]
};
